name: Auto Versioning

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Current Sha
        run: |
          if git rev-parse HEAD^2 >/dev/null 2>&1; then
            echo "current_sha=$(git rev-parse HEAD^2)" >> $GITHUB_ENV
          else
            echo "current_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV
          fi

      - name: Generate trunkver
        id: trunkver
        uses: crftd-tech/trunkver@main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run versioning script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ env.current_sha }}
          TRUNKVER: ${{ steps.trunkver.outputs.trunkver }}
        run: node .github/scripts/versioning.cjs