name: Notify on dependencies update
on:
  pull_request:
    branches:
      - prod
    types: [closed]

jobs:
  job:
    runs-on: ubuntu-slim
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, format('type{0} dependencies', ':')) }}
    steps:
      - name: Notify team
        run: |
          curl -X POST "${{ secrets.TEAMS_DEPENDENCY_NOTIFICATION_URL }}"