name: Prepare Deploy

on:
  workflow_dispatch:
    inputs:
      commitHash:
        required: true

permissions:
  contents: write
  pull-requests: write

env:
  BRANCH_NAME: deploy/${{ inputs.commitHash }}

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create deploy branch and push
        run: |
          git switch --create "$BRANCH_NAME" ${{ inputs.commitHash }}
          git push origin -f "$BRANCH_NAME"

      - name: Generate release notes using GitHub API
        id: release_notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sha=${{ inputs.commitHash }}
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="$sha" \
            -f target_commitish="$sha" \
            > generated_notes.json

          jq -r '.body' generated_notes.json > pr_body.txt

      - name: Create Pull Request to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "$BRANCH_NAME" \
            --body-file pr_body.txt \
            --base prod \
            --head "$BRANCH_NAME"
