name: Prepare Deploy 

on:
  workflow_dispatch:
    inputs:
      commitHash:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate trunkver
        id: trunkver
        uses: crftd-tech/trunkver@main

      - name: Checkout commit and create release branch
        run: |
          git fetch origin
          git checkout ${{ inputs.commitHash }}
          branch_name="release/${{ steps.trunkver.outputs.trunkver }}"
          echo "branch_name=$branch_name" >> $GITHUB_ENV
          git switch -c "$branch_name"
          git push origin -f "$branch_name"

      - name: Generate release notes using GitHub API
        id: release_notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="${{ steps.trunkver.outputs.trunkver }}" \
            -f target_commitish="release/${{ steps.trunkver.outputs.trunkver }}" \
          > generated_notes.json

          jq -r '.body' generated_notes.json > pr_body.txt

      - name: Create Pull Request to prod
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "release/${{ steps.trunkver.outputs.trunkver }}" \
            --body-file pr_body.txt \
            --base prod \
            --head "release/${{ steps.trunkver.outputs.trunkver }}"
