name: Deploy

on:
  workflow_dispatch:
    inputs:
      commitHash:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Current Sha
        run: echo "current_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create release branch and force push
        run: |
          git checkout ${{ inputs.commitHash }}
          branch_name="release/${{ inputs.commitHash }}"
          git switch -c "$branch_name"
          git push origin "$branch_name"

      - name: Generate release notes using GitHub API
        id: release_notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="${{ inputs.commitHash }}" \
            -f target_commitish="${{ env.current_sha }}"
          > generated_notes.json

          cat generated_notes.json | jq -r '.body' > pr_body.txt

      - name: Create Pull Request to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name="release/${{ inputs.commitHash }}"
          gh pr create \
            --title "Deploy: $branch_name" \
            --body-file pr_body.txt \
            --base main \
            --head "$branch_name"