name: TrunkVer

on:
  workflow_dispatch:
    inputs:
      commitHash:
        required: true
      buildId:
        required: false
      draft:
        required: false
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Generate trunkver
        id: trunkver
        uses: crftd-tech/trunkver@main

      - name: Print trunkver
        with:
          ref: ${{ inputs.commitHash }}
          fetch-depth: 0
        env:
          TRUNKVER: ${{ steps.trunkver.outputs.trunkver }}
        run: |
          echo "$TRUNKVER"
